# Site settings
title: LFP Arquiterura
email: your-email@domain.com
description: Projetos de arquitetura/
email: lfp@gmail.com
description: Arquitetura e projetos.
full_url: "http://lfparquitetura.com.br/"
twitter_username: jekyllrb
github_username:  beatrizcp87

# Build settings
markdown: kramdown
