# Site settings
title: LFP Arquiterura
email: your-email@domain.com
description: Projetos de arquitetura/
email: lfp@gmail.com
description: Arquitetura e projetos.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  beatrizcp87

# Build settings
markdown: kramdown
