# Site settings
title: Eólica
email: blogeolica@gmail.com
description: Blog sobre livros e séries. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eolica.com" # the base hostname & protocol for your site
twitter_username: #nenhum
github_username:  #nhenhum

# Build settings
markdown: kramdown
