# Site settings
title: Eólica
email: blogeolica@gmail.com
description: Blog sobre livros e séries. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: bloageolica
github_username:  blogeolica

# Build settings
markdown: kramdown
