# Site settings
title: Eolica
email: your-email@domain.com
description: Literatura fantástica e ficção científica.
email: blogeolica@gmail.com
description: Literature blog.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  beatrizcp87

# Build settings
markdown: kramdown
