# Site settings
title: LFP Arquiterura
email: your-email@domain.com
description: Projetos de arquitetura/
email: lfp@gmail.com
description: Arquitetura e projetos.
url: "http://beatrizcp87.github.io/lfp-arquitetura/
twitter_username: jekyllrb
github_username:  beatrizcp87

# Build settings
markdown: kramdown
